### PR TITLE
Pr/3

### PR DESCRIPTION
**Pull request by shakalaca**

### CODE REVIEW

**Comment by gwenhael-le-moine** [comment]
Works for me :)

**Comment by shakalaca** [comment]
Thanks for your quick reply, I'm not familiar with pull request on github (only did this on bitbucket) so I want to ask: should I just merge this one or wait for your update on the original pull request then close this one ? Really thanks for your patience :)

**Comment by gwenhael-le-moine** [comment]
I'm no expert in PR either, I think you should merge this one.

**Comment by shakalaca** [comment]
Got it ! :)

**Pull request merged**
